### ISSUE TITLE
Keep extended media window size consistent

### ISSUE THREAD

**Issue by manymanecki** [ccatterina/plasmusic-toolbar#102]
Issue: When clicked on, the player's window is sometimes very, very small. Can be expanded from that size, but also decreased to that size.

![Screenshot_20240605_180919](https://github.com/ccatterina/plasmusic-toolbar/assets/68863735/b74b1eb4-10a6-40b9-9a39-71bc1a960da2)

**Comment by ccatterina** [comment]
Thank you for reporting this.

Can you give me some more details:
- Which KDE Plasma version are you using?
- Are you using the default KDE panel or something else?

Thanks again!

**Comment by manymanecki** [comment]
> Thank you for reporting this.
> 
> Can you give me some more details:
> 
>     * Which KDE Plasma version are you using?
> 
>     * Are you using the default KDE panel or something else?
> 
> 
> Thanks again!

KDE Plasma 6. Default panel.
![image](https://github.com/ccatterina/plasmusic-toolbar/assets/68863735/d6357886-a10b-492b-a379-f1e5be5368d3)

**Comment by ccatterina** [comment]
Hi!
I've tried to replicate it in a VM with EndeavourOS 2024.04.20 but I can't.
Can you check which plasma version do you have excactly? 6.0.3, 6.0.4, 6.0.5?

I know that there was similar errors with the system tray widget in plasma 6.0.3 and 6.0.4:
- https://discuss.kde.org/t/system-tray-is-acting-weird-plasma-6-0-4-endeavour-os/14269
- https://www.reddit.com/r/kde/comments/1c3pwuq/system_tray_doesnt_open/

**Comment by manymanecki** [comment]
Hey, really sorry for keeping you in the dark for so long. For the answers:
- Issue still persistent in KDE Plasma 6.1 (this issue was opened  on an earlier undisclosed version)
- Does not seem related with any of those two issues you have linked
For some more information:
OS: EndeavourOS
Kernel: 6.9.5-arch
WM: Wayland
DM: KDE Plasma 6.1.0 (Frameworks: 6.3.0)
Qt: 6.7.1

Do not hesitate to ping me for further information on how to reproduce it, this time I should be faster:)

**Comment by manymanecki** [comment]
https://github.com/ccatterina/plasmusic-toolbar/assets/68863735/733f1060-ff50-440b-91b7-0578e0c51ab9

Quick video for reference.

**Comment by ccatterina** [comment]
Hi!
No problem, and thank you the video, now I understand what you meant! I should be able to work on this in the next week! 🙂

**Comment by luisbocanegra** [comment]
@manymanecki Can you check if https://github.com/ccatterina/plasmusic-toolbar/pull/110 fixes it? 

The change just avoids resizing the widget past the content size, so I am not sure if it will fix the size being very small by default (always opened with the correct size for me before that change)

**Comment by ccatterina** [comment]
@manymanecki a possibile fix (#110) has been released, feel free to reopen this if the issue stil occurs.
