### ISSUE TITLE
Title always scrolls when seperate lines enabled

### ISSUE THREAD

**Issue by Tech-How** [ccatterina/plasmusic-toolbar#103]
Hi, I've found a bug where if you enable the track and artist showing in separate lines, and then set the scrolling behavior to only scroll on mouse over, it will always start scrolling when a new media session starts.

To reproduce:
- Enable separate lines, and set it to only scroll on mouse hover
- Close and re-open a program with a long track/title name, so it scrolls
- Observe how it scrolls.

Next, move your mouse cursor on the title, and the back off. Now, until a new session is started, it will respond correctly.

Expected:
The scrolling always starts in the "off" position when only scroll on mouse hover is set.

**Comment by ccatterina** [comment]
Thank you for the detailed report! I will look into in the next week!

**Comment by Tech-How** [comment]
Just an update, I disabled separate lines and the issue still occurs. Not exactly sure what could be causing it.
