### ISSUE TITLE
Mouse wheel shortcuts akin to plasma's media player widget

### ISSUE THREAD

**Issue by AuraHerreroRuiz** [ccatterina/plasmusic-toolbar#115]
Something I'd like to see for this plasmoid is to add the actions the normal media player plasmoid has: Increase and decrease the current player's volume using the scroll wheel, and pause/resume on middle click.

**Comment by luisbocanegra** [comment]
Added in #117, please test it out

![Screenshot_20240721_194441](https://github.com/user-attachments/assets/b1d69ec9-80f6-404f-be3b-b364bbf3994b)

Should the step size be configurable? I left it fixed to 5%

**Comment by AuraHerreroRuiz** [comment]
> Added in #117, please test it out

Works perfectly! Thanks a lot for adding it.

> Should the step size be configurable? I left it fixed to 5%

Hmm, from what I can tell, Plasma's default mediaplayer widget follows the volume step size specified in settings, just like the volume widget. (Input & Output > Sound > Configure Volume Controls...)
![22-07_14-18_0001](https://github.com/user-attachments/assets/64a02833-2df3-4093-9c93-4f24d2d81333)

I feel it should follow that, if possible.

**Comment by luisbocanegra** [comment]
> Hmm, from what I can tell, Plasma's default mediaplayer widget follows the volume step size specified in settings, just like the volume widget. (Input & Output > Sound > Configure Volume Controls...)

Added, the cpp plugin from the default media player provides that https://github.com/KDE/plasma-workspace/tree/master/applets/mediacontroller/plugin (`import org.kde.plasma.private.mediacontroller 1.0`)

In theory, the default media player widget should always be shipped with Plasma, but since it is no longer a hard requirement to have working media shortcuts after [MR applets/mediacontroller: port away from DataEngine](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/2895) ([BUG 409190](https://bugs.kde.org/show_bug.cgi?id=409190)) I will add a conditional import and fallback to 5 if the module can't be imported.

**Comment by ccatterina** [comment]
> Added, the cpp plugin from the default media player provides that https://github.com/KDE/plasma-workspace/tree/master/applets/mediacontroller/plugin (import org.kde.plasma.private.mediacontroller 1.0)
>
> In theory, the default media player widget should always be shipped with Plasma, but since it is no longer a hard requirement to have working media shortcuts after [MR applets/mediacontroller: port away from DataEngine](https://invent.kde.org/plasma/plasma-workspace/-/merge_requests/2895) ([BUG 409190](https://bugs.kde.org/show_bug.cgi?id=409190)) I will add a conditional import and fallback to 5 if the module can't be imported.

@luisbocanegra @AuraHerreroRuiz 
I'm not very sure if it's worth doing this; I would prefer not to couple this widget too much with the media controller. For now, IMO it can remain a non-configurable value but if you guys prefer to make it configurarable we can add a new option in the settings.

**Comment by luisbocanegra** [comment]
> I'm not very sure if it's worth doing this; I would prefer not to couple this widget too much with the media controller.

Understandable, reverted it back to 5%.

> For now, IMO it can remain a non-configurable value but if you guys prefer to make it configurarable we can add a new option in the settings.

Personally, I never change the default on Plasma either, but for the people that do, an option that allows them to manually match the rest of the system could be nice IMHO.

**Comment by ccatterina** [comment]
> Personally, I never change the default on Plasma either, but for the people that do, an option that allows them to manually match the rest of the system could be nice IMHO.

:+1: it's fine for me!
