### ISSUE TITLE
Colors from album cover

### ISSUE THREAD

**Issue by luisbocanegra** [ccatterina/plasmusic-toolbar#120]
I have been thinking of adding this feature for some time, today I was experimenting and came up what you see below ([still wip](https://github.com/luisbocanegra/plasmusic-toolbar/tree/colors-from-cover-img))

Is this something you would like to have?

If it were to be added:
- Should allow to enable/disable the feature, I think it could be distracting having the colors changing all the time for some users
- Since the cover allows custom radius the background would need custom one too
- When there is no image which color should it fallback to?
- What about the expanded representation? Should the widget use colors from the album when placed on the Desktop?
- What else?

![append-2024-07-22-200105](https://github.com/user-attachments/assets/7b0c48f6-eb3f-4ee7-9728-4e63ee0c8da6)

**Comment by ccatterina** [comment]
Wow, what a really cool feature! :star_struck: 

> Should allow to enable/disable the feature, I think it could be distracting having the colors changing all the time for some users

Yeah, and I think this is something that would be disabled for default.

> Since the cover allows custom radius the background would need custom one too

yes, but it could be done in a second step IMO.

> When there is no image which color should it fallback to?

I would fallback to the current behaviour

> What about the expanded representation? Should the widget use colors from the album when placed on the Desktop?

This in my opinion could be an other separate feature, I've been wanting to implement something similar to this for quite a while now. I was thinking to use the dominant color as background and apply a fade effect to the album art (and maybe also a colored overlay), but I've never found an easy way to get the dominant color from the image, I didn't know about `Kirigami.ImageColors`!

**Comment by StrongSand94191** [comment]
this looks amazing!

**Comment by luisbocanegra** [comment]
Added control for radius and animation for color change, thoughts?

![image](https://github.com/user-attachments/assets/3a36e473-8a89-469b-8a09-74c893b5f5da)


[Screencast_20241115_014948.webm](https://github.com/user-attachments/assets/6d0ec66c-d2f9-4931-b265-68f74f5ead1c)

**Comment by luisbocanegra** [comment]
> shouldnt the border extend a bit further to the left, past the album cover

Yes, was waiting for https://github.com/ccatterina/plasmusic-toolbar/pull/149, will add it later today.

**Comment by luisbocanegra** [comment]
Ended up making the widget scale with the panel, now all sides have the same margin

Makes the tinted background look way better IMO:

[Screencast_20241115_211046.webm](https://github.com/user-attachments/assets/5302828d-264f-4d23-8f20-7bbe6036cc08)
