### ISSUE TITLE
Add feature to make widget transparent

### ISSUE THREAD

**Issue by luma-vpk** [ccatterina/plasmusic-toolbar#122]
Hello, i really love this plasmoid, but can you please add feature to make it transparent, or to change the opacity in settings. 

Thanks!

**Comment by ccatterina** [comment]
Hi! yes, it seems a nice feature, at the moment I'm a bit busy but I'll try to work on this in the next few weeks.

**Comment by luma-vpk** [comment]
> Hi! yes, it seems a nice feature, at the moment I'm a bit busy but I'll try to work on this in the next few weeks.

Thank you

**Comment by luma-vpk** [comment]
um accidentally closed sorry

**Comment by ccatterina** [comment]
Hi! I'm working on this. I found a way to make the widget transparent when it's used as a desktop widget:
![image](https://github.com/user-attachments/assets/6c83fc2a-628d-444a-8674-11060f101db7)

Unfortunately I can't find a way to make the widget transparent when it's used inside a panel. 
Do you use it as a panel or as a desktop widget?

**Comment by luma-vpk** [comment]
> Hi! I'm working on this. I found a way to make the widget transparent when it's used as a desktop widget: ![image](https://private-user-images.githubusercontent.com/9085116/357299515-6c83fc2a-628d-444a-8674-11060f101db7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzEyMjgsIm5iZiI6MTcyMzUzMDkyOCwicGF0aCI6Ii85MDg1MTE2LzM1NzI5OTUxNS02YzgzZmMyYS02MjhkLTQ0NGEtODY3NC0xMTA2MGYxMDFkYjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTNUMDYzNTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2IwMTBmNTcxYTAyMWM4Zjg5MzY3OWQyZDZhNTVmYjQ2NGE1ZWU1YmIxZGQwOWJjNzM5ZWYwMTNmNmVmMTE1YiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JEQA9H7_Ot3HjAq8epG10LknhzVP0matGd0xGOLouN8)
> 
> Unfortunately I can't find a way to make the widget transparent when it's used inside a panel. Do you use it as a panel or as a desktop widget?

thats cool, i use as a desktop widget

**Comment by luma-vpk** [comment]
ooh i again closed bruhh

**Comment by ccatterina** [comment]
I will merge the feature and release it this afternoon.

**Comment by luma-vpk** [comment]
good job!

**Comment by ccatterina** [comment]
Released, you can find a new option at the end of settings page.
