### ISSUE TITLE
Show fallback panel icon if no album cover is present.

### ISSUE THREAD

**Issue by StrongSand94191** [ccatterina/plasmusic-toolbar#123]
I like to have the "Use album cover as panel icon" option enabled because it looks really nice when there is album art:
![image](https://github.com/user-attachments/assets/0e48e5e2-5880-48f0-af06-bf8d339e7132)

However, when media is playing with no album art, such as from YouTube, it doesn't show a panel icon at all:
![image](https://github.com/user-attachments/assets/2c03e74e-3ea4-4d55-a0e2-bf777dd0dfa5)

It would be cool if it would just show the default panel icon.
Thank you!

**Comment by ccatterina** [comment]
Released, I add an option into the settings page to enable this behaviour.
