### ISSUE TITLE
Webp album cover support

### ISSUE THREAD

**Issue by StrongSand94191** [ccatterina/plasmusic-toolbar#130]
Many sites like YouTube use .webp files as album covers, so this would fix blank album covers for a lot of cases

**Comment by ccatterina** [comment]
Hi!
I'm using the QML Image type that apparently doesn't support the `.webp` format (https://doc.qt.io/qt-6/qimage.html#reading-and-writing-image-files).
It seems that exists a qt plugin to add support for additional formats (https://doc.qt.io/qt-6/qtimageformats-index.html), but I can't understand if I can include it in the plasmoid or if it should be installed in the system that use the plasmoid.

**Comment by luisbocanegra** [comment]
It needs to be installed on the system, on Arch it's [qt6-imageformats](https://archlinux.org/packages/extra/x86_64/qt6-imageformats/).
I have it installed and WebP covers/thumbnails are displayed correctly.

**Comment by StrongSand94191** [comment]
This worked, thanks!
