### ISSUE TITLE
Play controls are greyed out and don't work

### ISSUE THREAD

**Issue by ciachciarachciach666** [ccatterina/plasmusic-toolbar#131]
Hey,

I upgraded to beta of Fedora 41 (Plasma 6.1.4, KDE Framework 6.5.0, Qt 6.7.2) and unfortunately while plasmusic still works, I can't get playback controls to work. I've reinstalled plasmusic already but I'm having the same issue.

Thanks!

**Comment by ccatterina** [comment]
Hi!
Can you check if the default KDE media player widget has the same issue?

**Comment by ciachciarachciach666** [comment]
Hey man!

I honest to God have no idea what happened but I locked my PC, came back few minutes later and it's working now. My apologies, will close this issue.

Thanks!
