### ISSUE TITLE
bring player to the front on toolbar icon/album cover click

### ISSUE THREAD

**Issue by ccatterina** [ccatterina/plasmusic-toolbar#14]
Bring the current player to the front when the toolbar icon is clicked. Datasource Raise operation should do the job.

UPDATE:
Open the media source when the user CTRL-Click the icon on the toolbar or when it click the on album cover in the maximized view.
suggested by @barisgirismen

**Comment by luisbocanegra** [comment]
Started implementing this on https://github.com/ccatterina/plasmusic-toolbar/pull/111 but have a couple of questions:

- Should something here be configurable?
- Should the cover have any hover/press feedback, maybe a small tooltip idk? Though for the cover on the panel it doesn't make much sense unless the Ctrl modifier is optional or such key press can be intercepted.

**Comment by ccatterina** [comment]
@luisbocanegra 
First of all, thank you for working on this ! 

> Should something here be configurable?

I would leave it unconfigurable for now

> Should the cover have any hover/press feedback, maybe a small tooltip idk? 

yes a little tooltip on the cover sounds like a good idea to me, maybe something like "Bring player to the front".

> Though for the cover on the panel it doesn't make much sense unless the Ctrl modifier is optional or such key press can be intercepted.

I agree, maybe we should mention this feature somewhere in the `Features` section in the README. Otherwise there is no way for the user to know about this

Thanks again!

**Comment by luisbocanegra** [comment]
Added the tooltip to the full representation, added a secondary message in case a player can't be raised. Should I add some effect to the hovered image?

![append-2024-07-06-234200](https://github.com/ccatterina/plasmusic-toolbar/assets/15076387/b7e033d3-d93c-4839-831a-ec385407f63e)


For the Ctrl+Click action I was thinking we can mention it in the default tooltip, sort of what the default Volume and other widgets do?

Also, could we intercept that in the whole widget and fallback to other actions when the modifier is not used or will that be an overkill?

**Comment by ccatterina** [comment]
> Added the tooltip to the full representation, added a secondary message in case a player can't be raised. Should I add some effect to the hovered image?

No, it's already fine without the effect IMO.

> For the Ctrl+Click action I was thinking we can mention it in the default tooltip, sort of what the default Volume and other widgets do?

yeah, that's fine!

> Also, could we intercept that in the whole widget and fallback to other actions when the modifier is not used or will that be an overkill?

Do you mean the whole panel widget (the compactRepresentation), right? It seems a great idea to me! If it's not a problem for you I would proceed like this.


Another little thing, could you rewrite the commit message in such a way that respect the [convetional commit](https://www.conventionalcommits.org/en/v1.0.0/) standard? 
I use [release-please](https://github.com/googleapis/release-please) which relies on convetional commit messages to automate changelog and releases creation.

**Comment by luisbocanegra** [comment]
> Do you mean the whole panel widget (the compactRepresentation), right?

Yes added to latest revision, only thing is I couldn't find how to make the buttons below respond and had to fill them with mouseareas, is that okay?

> Another little thing, could you rewrite the commit message in such a way that respect the [convetional commit](https://www.conventionalcommits.org/en/v1.0.0/) standard?

Done
