### ISSUE TITLE
Suggestion: Option to "fill width" of panel

### ISSUE THREAD

**Issue by AuraHerreroRuiz** [ccatterina/plasmusic-toolbar#142]
This widget has been for me an excellent replacement for the MediaPlayer+ Plasma 5 widget, but I would hugely appreciate an option for the widget to fill the width of the panel as MediaPlayer+ has.

My setup with the MediaPlayer+ widget was like this:

![image](https://github.com/user-attachments/assets/f6aae6a9-fd85-46de-98bc-2193eac27588)

The widget was in the middle and it looked quite aesthetically pleasing as it was always centered, pushing the date and weather (in my case) to the left and all the system tray icons to the right, making it symetrical. The widget itself always pushed the media buttons to the rightmost edge, and the title and icon to the leftmost edge (with margins applied of course).

I can't do this with this widget, and trying to replicate the setup with spacers hasn't wielded good results, as the media button keep changing places with the songs text changing, messing up muscle memory of reaching towards them in the taskbar. 

I'll provide some image examples:

Example with spacers:

![image](https://github.com/user-attachments/assets/3b3e35ac-a29a-4755-9112-4f78ea239173)

This just centers the entire widget. When changing songs, the widget moves, being distracting and messing with muscle memory:

![image](https://github.com/user-attachments/assets/37832c13-4ade-434f-8ad5-3aba86f41e69)
![image](https://github.com/user-attachments/assets/29752f1e-98d2-45bf-8b85-00697fbb43c3)

Plus, the spacers don't do anything useful, while if the widget filled the entire width itself, You would have a great area to click and access it, or to use the scroll wheel for volume.

The widget in this state when no media is playing just disappears (as far as I can tell its width just becomes 0), so perhaps it could keep the width or show some "No media playing" text so it wouldn't move the other widgets in the panel around.

I would hugely appreciate this feature, even if it might be a bit nieche.

**Comment by ccatterina** [comment]
Hi @AuraHerreroRuiz, thank for the suggestion, it seems a nice feature. In the next few weeks I'll make some tests.  

> The widget in this state when no media is playing just disappears (as far as I can tell its width just becomes 0), so perhaps it could keep the width or show some "No media playing" text so it wouldn't move the other widgets in the panel around.

Regarding this part I opened a separate issue https://github.com/ccatterina/plasmusic-toolbar/issues/143

**Comment by ccatterina** [comment]
Hi @AuraHerreroRuiz , I added a new option to make the widget fill the available space. Let me know if it's okay.

**Comment by AuraHerreroRuiz** [comment]
I've tested it and it works perfectly! Thank you very much for taking your time to implement it.
