### ISSUE TITLE
Vertical panel support

### ISSUE THREAD

**Issue by luisbocanegra** [ccatterina/plasmusic-toolbar#147]
Hi, what do you think about implementing support for vertical panels? I was experimenting with the widget but figured it will be better to ask you first and agree on a design (if you want the widget to support for this of course).

Some ways I think this can be implemented:

Option 1 rotate the RowLayout

![image](https://github.com/user-attachments/assets/34121914-2b37-4f96-a1f1-3925feaf6316)

Option 2 swap columns/rows using GridLayout

![image](https://github.com/user-attachments/assets/8f5cabf9-edca-4fb2-b28d-3b48a3ade499)

**Comment by ccatterina** [comment]
Hi @luisbocanegra, it seems a nice feature to me.
I would go with the option 2, it would seem a little strange to me to click on the rotated buttons. How the expanded representation would appear with the vertical panel?
Thank you very much! :slightly_smiling_face:

**Comment by luisbocanegra** [comment]
> I would go with the option 2, it would seem a little strange to me to click on the rotated buttons.

I like that one more too.

> How the expanded representation would appear with the vertical panel?

It would look the same, no changes there



![append-2024-11-14-111139](https://github.com/user-attachments/assets/56c66b8e-0453-4347-8609-dccba3706775)

**Comment by ccatterina** [comment]
> > I would go with the option 2, it would seem a little strange to me to click on the rotated buttons.
> 
> I like that one more too.
> 
> > How the expanded representation would appear with the vertical panel?
> 
> It would look the same, no changes there
> 
> 
> 
> ![append-2024-11-14-111139](https://github.com/user-attachments/assets/56c66b8e-0453-4347-8609-dccba3706775)
> 

👍 great!
