### ISSUE TITLE
Porting to KDE6

### ISSUE THREAD

**Issue by ccatterina** [ccatterina/plasmusic-toolbar#16]
https://develop.kde.org/docs/plasma/widget/porting_kf6/

**Comment by KottV** [comment]
Hi,
It would be nice as KDE 6 is approaching.

**Comment by ccatterina** [comment]
yep, I'm working on it!
It's a bit more difficult than expected because the mpris2 data source has been replaced with a new model.
Anyway I'll try to release a KDE 6 version before the end of January.

**Comment by ccatterina** [comment]
Hi @KottV, I wanna let you know that I'm a bit late with the porting to KDE 6 but it's almost done, probably next week I should be able to release it.
There is already a working branch https://github.com/ccatterina/plasmusic-toolbar/tree/plasma6 but I should test and refactor it a bit before release it.

**Comment by KottV** [comment]
Hi!

Absolutely no worries and thanks for the info.
In my turn I had to switch back to KDE5, so I can test plasma6 branch in next week also or so.
