### ISSUE TITLE
Use a placeholder image when there is no `artUrl` available

### ISSUE THREAD

**Issue by ccatterina** [ccatterina/plasmusic-toolbar#17]
Now it shows a white square

**Comment by tretdm** [comment]
![изображение](https://github.com/ccatterina/plasmusic-toolbar/assets/76806170/16c2f5c6-87c7-41bc-9a2f-2ae9bc06f684)

This widget receives playback information from KDE Connect, but KDE Connect does not receive the cover information and the widget shows the same blank cover.

**Comment by ccatterina** [comment]
Hi @tretdm
Not much can be done to show the cover if the widget doesn't receive the album image URL. I prioritize this issue so we can, at least, show a placeholder instead of a blank cover.
Thank you!
