### ISSUE TITLE
Preferred MPRIS2 source set to Spotify doesn't do anything

### ISSUE THREAD

**Issue by boobthecat** [ccatterina/plasmusic-toolbar#18]
When trying to use the widget with the MPRIS2 source set to @multiplex works fine but It detects any video you're playing on the browser. So switching the option to spotify only would solve but it doesn't do anything once you restart the PC.

**Comment by ccatterina** [comment]
Thank you for opening the issue, @boobthecat!

Can you explain in a little more detail what happens when you change the preferred source:
- Before restart the PC the widget works?
- The widget doesn't work at all anymore or it continues to work as if it has the preferred source set to `@multiplex`?

**Comment by boobthecat** [comment]
Thank you! =)

**Comment by ccatterina** [comment]
@boobthecat I released a new version with the fix. Please let me know if the problem is fixed! Thank you

**Comment by boobthecat** [comment]
Yep, working just fine now! Now we only need a smoother text scroll and voila
