### ISSUE TITLE
Alignment

### ISSUE THREAD

**Issue by GkhnGRBZ** [ccatterina/plasmusic-toolbar#2]
Hello. When I add it to the latte dock panel, it looks like the picture. Is there any way to fix this?

![Screenshot_20230926_193758](https://github.com/ccatterina/plasmusic-toolbar/assets/127258824/62c383c1-4f82-4cc5-8c1c-3955d5ce305e)

**Comment by ccatterina** [comment]
Thank you for opening the issues. I think I'll be able to take a look at it in the next week.

**Comment by ccatterina** [comment]
@GkhnGRBZ  I released a new version of the widget, can you give it a try?

**Comment by GkhnGRBZ** [comment]
I've tried. Thank you. Everything is very good.

I have a suggestion. It would be great if the text scrolling was like ticki and the icon size was a little larger.

**Comment by ccatterina** [comment]
Great!! 👍👍

What do you mean with "ticki"?

Regarding the icon size, I could make It configurable, I noticed that the size differs really much depending on the icon set that you are using.

**Comment by GkhnGRBZ** [comment]
You're welcome. I leave Ticki's URL. I'm also sending a small video to your email address.

https://store.kde.org/p/1596560

Thank you for your interest.

**Comment by ccatterina** [comment]
Ok, it's clear now...I will let you know when I have some updates! thank you
