### ISSUE TITLE
Add an option to disable song title scrolling

### ISSUE THREAD

**Issue by ccatterina** [ccatterina/plasmusic-toolbar#45]

**Comment by Tech-How** [comment]
I agree with this too. An option to disable scrolling entirely, and another checkbox "Reset position on mouse off"

**Comment by luisbocanegra** [comment]
Added in #119, please test it out

Update from the current version
```
git clone https://github.com/luisbocanegra/plasmusic-toolbar.git -b disable-text-scrolling
cd plasmusic-toolbar && kpackagetool6 -t Plasma/Applet -u src
```
Then logout/reboot/restart plasmashell

**Comment by luisbocanegra** [comment]
Demo:

https://github.com/user-attachments/assets/978e682e-c799-480f-99bf-be14d9bda27f
