### ISSUE TITLE
Text is no longer centred when the maximum width change

### ISSUE THREAD

**Issue by ccatterina** [ccatterina/plasmusic-toolbar#46]

**Comment by quoije** [comment]
Hi @ccatterina, love the widget. 
Was wondering if that was related to this bug:
![Screenshot_20240123_192925](https://github.com/ccatterina/plasmusic-toolbar/assets/6080400/6e228564-af91-4309-8ac6-c101d009a1f2)

I'm having this issue when the text is cutoff on the right and is cutting an character of the song name. 
Try to the change the maximum width but with no change. 

If there a quick fix I could do while waiting for the next release, that would be cool ;)

**Comment by ccatterina** [comment]
hi @quoije , thank you for the report,  I will look at it in the next few days.
Unfortunately I think there isn't a quick fix.

**Comment by ccatterina** [comment]
The bug seems no longer present in the version v1.0.5.
