### ISSUE TITLE
Song text is cut off

### ISSUE THREAD

**Issue by ccatterina** [ccatterina/plasmusic-toolbar#50]
Song text is cut off, changing the `Panel song max width` don't solve the problem.
Reported by @quoije  https://github.com/ccatterina/plasmusic-toolbar/issues/46#issuecomment-1907147632

**Comment by ccatterina** [comment]
hi @quoije , I can't reproduce the bug. Could you post your plasmusic configuration?

**Comment by ccatterina** [comment]
Hi @quoije 
are you still using the widget? If you are using KDE 6 can you try if the bug is still present in the last version of the widget?
Thank you!

**Comment by quoije** [comment]
Hi Claudio,
Sorry for my lack of response regarding this issue.

Unfortunately, I don't have access to my Linux box I was using when I
discovered this bug, however I’m glad this is resolved.

I'll let you know when I reinstall KDE with the same config I was using
back then.

Thanks for your work.
