### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by SmollClover** [ccatterina/plasmusic-toolbar#61]
I updated to Plasma 6 today and noticed that the Plasmusic Widget isn't working on it.  

```
This Widget was written for an unknown older version of Plasma and is not compatible with Plasma 6. 
Please contact the widget's author for an updated version.
```

**Comment by ccatterina** [comment]
Hi @SmollClover 

Which version did you installed? Plasma 6 should be supported from v1.0.0.

In the kde store there are 2 version available:
Plasma 6: https://store.kde.org/p/2128143
Plasma 5: https://store.kde.org/p/2088872

**Comment by SmollClover** [comment]
> If you upgraded from Plasma 5 to Plasma 6 you probably need to uninstall the old widget and install the new version

Yep, that fixed it for me.  
I didn't realize that Discover wouldn't just automatically be able to update from the old to the new widget, which made me think that there wasn't any support for Plasma 6. After now uninstalling and reinstalling the widget, it's now fixed without any hiccups.

Thank you for your help!
