### ISSUE TITLE
Cannot detect Elisa as an MPRIS2 source

### ISSUE THREAD

**Issue by Futhorka** [ccatterina/plasmusic-toolbar#62]
I don't know if I'm doing something wrong, but I cannot set it to detect Elisa as a source. Which is strange because it detects it just fine when set to “any”.

I tried setting source to:

- elisa
- Elisa
- org.kde.elisa
- elisa org.kde.elisa

but got no luck.

**Comment by ccatterina** [comment]
Mmm... that's strange, I tried `org.kde.elisa` and it seems to work. Can you check that the configuration attributes `sources` and `sourceIndex` are correctly configured? They should be stored in  `~/.config/plasma-org.kde.plasma.desktop-appletsrc`

You can find them with:
- `cat ./.config/plasma-org.kde.plasma.desktop-appletsrc | grep sources`
- `cat ./.config/plasma-org.kde.plasma.desktop-appletsrc | grep sourceIndex`

**Comment by CreonThCa** [comment]
I just tried again and for some reason one that you provided (`org.kde.elisa`) worked but one that I provided(`org.kde.elisa`) doesn't work.

I'm not sure what the difference is.

**Comment by ccatterina** [comment]
While I was doing some tests I noticed that after you change the source in the configuration page you need to close and reopen the corresponding player to make the widget recognize the correct source. I will fix it in the next release. Thank you for reporting this!
