### ISSUE TITLE
[Bug]The strange operation logic of the progress bar

### ISSUE THREAD

**Issue by Crany-web** [ccatterina/plasmusic-toolbar#63]
This plug-in is very good, but after using it for a long time, I discovered one of the flaws, that is, I cannot easily control the playback progress of the music through the plug-in's progress bar. Dragging the plug-in's progress bar will make the music play faster or rewind a few seconds. If If I want to go back to the beginning of the song, I can only click on the left side of the progress bar frequently.See the link for details  https://github.com/Crany-web/log/blob/main/Recording%202024-03-09%20at%2016.31.03.gif

**Comment by ccatterina** [comment]
Hi @Crany-web 
Thank you for reporting this.
Unfortunately with my setup I can't reproduce it. Which version of plasma and which music player are you using?

**Comment by Crany-web** [comment]
> Hi @Crany-web Thank you for reporting this. Unfortunately with my setup I can't reproduce it. Which version of plasma and which music player are you using?

I am using KDE 6, the version is 6.0.1-1. As for the music players that are currently experiencing this issue, there are GitHub projects YesPlayMusic and lx-music-desktop.

**Comment by ccatterina** [comment]
Thank you, I make some test and I let you know

**Comment by Crany-web** [comment]
> 谢谢，我做了一些测试，然后告诉你

Hello developer, thank you very much for noticing the problem I submitted. This is not to urge you, but I am curious whether you can reproduce this bug or are you currently fixing it?

**Comment by ccatterina** [comment]
Hi,
I released a new version that could fix this issue, can you give it a try? Check that the version of the widget in the configuration panel is `1.0.2`.

![image](https://github.com/ccatterina/plasmusic-toolbar/assets/9085116/1b8f56cd-7fe9-45ea-a7fc-2a71e45e490e)

**Comment by Crany-web** [comment]
> ccatterina

Hello ccasterina, after receiving your message, I immediately upgraded the plug-in and found that the issue has been fixed. Thank you for your help.

**Comment by ccatterina** [comment]
Great! Thank you!
