### ISSUE TITLE
Mention AUR package in README

### ISSUE THREAD

**Issue by D3SOX** [ccatterina/plasmusic-toolbar#69]
Hey great plasmoid, I created an AUR package as an installation method.

You can integrate it into the README however you like
For example as command
```bash
(command -v paru && paru -S plasma6-applets-plasmusic-toolbar) || yay -S plasma6-applets-plasmusic-toolbar
```

as a badge

[![AUR Version](https://img.shields.io/aur/version/plasma6-applets-plasmusic-toolbar)](https://aur.archlinux.org/packages/plasma6-applets-plasmusic-toolbar)
```
[![AUR Version](https://img.shields.io/aur/version/plasma6-applets-plasmusic-toolbar)](https://aur.archlinux.org/packages/plasma6-applets-plasmusic-toolbar)
```

or just a link to https://aur.archlinux.org/packages/plasma6-applets-plasmusic-toolbar

Unrelated but I think `plasmapkg2` (which is used in the README) does not exist anymore with Plasma 6 (at least on my Arch system after upgrading)

**Comment by ccatterina** [comment]
:star_struck: thank you @D3SOX!
I add the badge and a paragraph in the installation section!

**Comment by ccatterina** [comment]
> Unrelated but I think plasmapkg2 (which is used in the README) does not exist anymore with Plasma 6 (at least on my Arch system after upgrading)

Oh thanks, I will fix also this.

**Comment by ccatterina** [comment]
Done, let me know if it's ok and feel free to open a PR if you need to change something! Thanks again! :heart:

**Comment by D3SOX** [comment]
That's perfect, thanks
