### ISSUE TITLE
Plasmashell crashing

### ISSUE THREAD

**Issue by ciachciarachciach666** [ccatterina/plasmusic-toolbar#70]
Hello,

Sadly had some serious issues with this addon. Had to reboot after installation and plasmashell just started crashing, removed plasmusic, rebooted, plasmashell started. Tested it once more and plasmashell was crashing again.

OS: KDE neon 6.0 x86_64 
Kernel: 6.5.0-25-generic 
DE: Plasma 6.0.2

`journalctl /usr/bin/plasmashell`
shows plenty of following errors:
`kde.dataengine.mpris: mpris:trackid from "Spotify" does not conform to the MPRIS2 standard. Please report the issue to the developer.`

Sadly I couldn't copy errors from plasmashell error handler.

Any ideas what could be wrong?

**Comment by ccatterina** [comment]
Hi @ciachciarachciach666,
I'm sorry, that's really strange.

Some questions:
 - Did you add the widget to the panel before reboot the system? Did the widget initially work?
 - Have you changed some widget configuration?
 - Which version of spotify are you using?

I'll try to reproduce this using the same KDE Neon version, Kernel, and spotify application and I let you know.

**Comment by ciachciarachciach666** [comment]
Hey,

That's fine and I was really surprised too.

1. Yes, I added it to the panel. If it helps I've used the KDE addon picker and not manual installation.
2. Yes, I changed icon to album art, preferred source to spotify, added artist name to be displayed and scrolling to happen only on mouse hover.
3. I'm using flatpak, version 1.2.31.1205.g4d59ad7c.
4. About 14:00 GMT+1, so already the newest version.

**Comment by ciachciarachciach666** [comment]
Ok, managed to reproduce this issue and got a crash log.
`Application: plasmashell (plasmashell), signal: Aborted

[KCrash Handler]
#4  __pthread_kill_implementation (no_tid=0, signo=6, threadid=133812411961280) at ./nptl/pthread_kill.c:44
#5  __pthread_kill_internal (signo=6, threadid=133812411961280) at ./nptl/pthread_kill.c:78
#6  __GI___pthread_kill (threadid=133812411961280, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#7  0x000079b3a5442476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#8  0x000079b3a54287f3 in __GI_abort () at ./stdlib/abort.c:79
#9  0x000079b3a60db597 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#10 0x000079b3a60d67f5 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#11 0x000079b3a60dbfc3 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#12 0x000079b3a60a0387 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#13 0x000079b2c6d7762f in  () at /lib/x86_64-linux-gnu/libkmpris.so.6
#14 0x000079b3a603c3ce in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#15 0x000079b3a5eccd82 in QAbstractItemModel::rowsInserted(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#16 0x000079b3a5ec5a36 in QAbstractItemModel::endInsertRows() () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#17 0x000079b3a603c6ab in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#18 0x000079b3a5eccd82 in QAbstractItemModel::rowsInserted(QModelIndex const&, int, int, QAbstractItemModel::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#19 0x000079b3a5ec5a36 in QAbstractItemModel::endInsertRows() () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#20 0x000079b2c6d8dcb1 in MultiplexerModel::updateActivePlayer() () at /lib/x86_64-linux-gnu/libkmpris.so.6
#21 0x000079b3a5fcc9b2 in QObject::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#22 0x000079b3a81f181b in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt6Widgets.so.6
#23 0x000079b3a6075e08 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#24 0x000079b3a6076000 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#25 0x000079b3a5e584f7 in  () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#26 0x000079b3a487ad3b in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x000079b3a48d0258 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x000079b3a48783e3 in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x000079b3a5e55c30 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#30 0x000079b3a607fceb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#31 0x000079b3a607a36c in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt6Core.so.6
#32 0x000060efeafdda94 in  ()
#33 0x000079b3a5429d90 in __libc_start_call_main (main=main@entry=0x60efeafdca50, argc=argc@entry=2, argv=argv@entry=0x7ffe00c454f8) at ../sysdeps/nptl/libc_start_call_main.h:58
#34 0x000079b3a5429e40 in __libc_start_main_impl (main=0x60efeafdca50, argc=2, argv=0x7ffe00c454f8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe00c454e8) at ../csu/libc-start.c:392
#35 0x000060efeafddd25 in  ()
[Inferior 1 (process 2105) detached]`

Manually removed plasmusic and plasmashell restarted without any issues. This is really weird.

**Comment by ccatterina** [comment]
Thank you for the detailed report! :pray: 

 I'll make some tests in the next few days and I let you know!

**Comment by ccatterina** [comment]
Hi @ciachciarachciach666 ,

I think it was this commit  0844cbc3d390a661121c01d62d17c97a758c0453 the cause of the issue. I reverted it and I released a new version of the widget in the kde store.
Let me know if it works, thank you so much! :pray:

**Comment by ciachciarachciach666** [comment]
Works! Thanks a lot for a quick fix!
