### ISSUE TITLE
smoother text scrolling animation

### ISSUE THREAD

**Issue by ccatterina** [ccatterina/plasmusic-toolbar#9]

**Comment by ccatterina** [comment]
@boobthecat @GkhnGRBZ

I released a new version with a smoother text scrolling animation, let me know what you think!

**Comment by GkhnGRBZ** [comment]
> @boobthecat @GkhnGRBZ
> 
> I released a new version with a smoother text scrolling animation, let me know what you think!

it's just perfect

**Comment by boobthecat** [comment]
> @boobthecat @GkhnGRBZ
> 
> 
> 
> I released a new version with a smoother text scrolling animation, let me know what you think!

Awesome! Thank you!
