### ISSUE TITLE
add support for smplayer

### ISSUE THREAD

**Issue by manoflinux** [ccatterina/plasmusic-toolbar#91]
it works great with VLC, but would like it to work with smplayer, if you haven't tried it you should.

**Comment by ccatterina** [comment]
Hi! I tried the widget with smplayer and it seems to work fine. What wasn't working?

**Comment by manoflinux** [comment]
should I just multiplex instead of vlc?  I was expecting it to show up in the list, but if multiplex is a generic setting I will try that.

**Comment by manoflinux** [comment]
OK something weird happened when I tried it with multiplex, pressing pause paused smplayer just as expected. when I tried it to play it again it said something like  "tor browser is playing media" and tor browser isn't running. but then I closed smplayer and reopened it and it worked normally.  when smplayer's playlist support gets updated and I can switch over to it I will test it further. it maybe just be something on my system. 
But either way thanks for looking into this.

**Comment by ccatterina** [comment]
Oh ok, I didn't understand that you wanted to set `smplayer` as the preferred source. The `Preferred MPRIS2 source` drop-down can be also used to add a new custom source.
You can write the text `smplayer` in the drop-down input, press enter, and apply the changes.

**Comment by manoflinux** [comment]
oh thanks

**Comment by manoflinux** [comment]
ok on 0.70 now and when I type in smplayer in the drop down input and hit ok and then look again it still shows the last thing it was set to(vlc). is this false and its actually pointed to smplayer after I type that in?

**Comment by ccatterina** [comment]
You need to type `smplayer` in the drop-down, press enter, and then press `Apply` button:
![Peek 2024-04-11 18-00](https://github.com/ccatterina/plasmusic-toolbar/assets/9085116/701fe864-23db-4800-af88-95791e723031)

**Comment by ccatterina** [comment]
I consider the issue resolved. If not, feel free to reopen it.
