### ISSUE TITLE
when using vlc the time left value is way off on long playtime videos. 

### ISSUE THREAD

**Issue by manoflinux** [ccatterina/plasmusic-toolbar#92]
when using vlc the time left value is way off on long playtime videos. 
Its usually way shorter, like I have seen a video that had 50 minutes left say there is 11 or 12 minutes left. 
But on shorter videos its fine. using version 0.6.0 
But other than that its works great, its very useful.

**Comment by ccatterina** [comment]
Hi @manoflinux 
This bug has been fixed on v1.0.5 that works only on KDE Plasma 6, I can backport the fix to the Plasma 5 version. I'll work on it in the next week!
Thank you for report!

**Comment by ccatterina** [comment]
I consider the issue resolved. If not, feel free to reopen it.
