### ISSUE TITLE
Add ability to change font/text display

### ISSUE THREAD

**Issue by nbt-x** [ccatterina/plasmusic-toolbar#94]
Most plasma widgets allow for changing the font. It would be really awesome if this one would too. An example of a widget that allows for this is the "Digital Clock" widget, where the font configuration can be found under Appearance>Text Display.
![image](https://github.com/ccatterina/plasmusic-toolbar/assets/95964582/ac8cd989-8f65-46f7-993d-5b6999498db4)
![image](https://github.com/ccatterina/plasmusic-toolbar/assets/95964582/ab875940-6e31-497d-9f03-5923380c8208)

I might give implementing this a shot myself but I have no experience making/working on plasma widgets.

Thanks for the awesome work done on this so far, it is a pleasure to use!

**Comment by ccatterina** [comment]
Hi @nbt-x 
Thank you for the suggestion, it could be a very useful feature!

If you'd like to try making a PR to implement the feature, that's great! I can also help you with it,  if you need any information, feel free to ask.

**Comment by ccatterina** [comment]
@nbt-x  In the next week maybe I will be able to work on it; if you want to try to implement it, let me know in the next 2-3 days so I will leave it with you. Thank you :slightly_smiling_face:
