### ISSUE TITLE
no longer get option for configuration menu and it doesn't show playing progress on the bar, it  stays at 0:00

### ISSUE THREAD

**Issue by manoflinux** [ccatterina/plasmusic-toolbar#96]
no longer get option for configuration menu and it doesn't show playing progress on the bar, it  stays at 0:00.
Its now on .71, the only reason I know this is I saw it update in discover.
Should I go back to .70?

**Comment by ccatterina** [comment]
That's strange, Have you already tried to log out and log in again, or reboot the PC? Can you try to uninstall and reinstall it?

**Comment by manoflinux** [comment]
working now, sorry

**Comment by manoflinux** [comment]
working now, sorry
